### ISSUE TITLE
confirmations not working

### ISSUE THREAD

**Issue by yasaricli** [ParsiCoin/parsicoin#7]
hi;

Payments made do not appear in confirmations.

<img width="559" alt="screen shot 2018-12-30 at 20 56 07" src="https://user-images.githubusercontent.com/1306620/50549855-7549f980-0c75-11e9-93c7-6940e44e2f80.png">

https://explorer.frontekip.com/transactions/f145285adc07de131a27895e8afe6907852045e68a5fe4c1ff28a4e4e09ffc68

thanks.

**Comment by ParsiCoin** [comment]
hello ,
is that a Transaction on ParsiCoin Network ?

**Comment by yasaricli** [comment]
no, own network [ekipcoin](https://github.com/Frontekip/ekipcoin). 

We are launching seed in this way.

    --enable-blockchain-indexes

**Comment by ParsiCoin** [comment]
if block synchronization across seednodes works , so it's not a seednode problem, it's maybe a chain split or something, i can see you forked a few days ago, there was some commits on master branch which we've removed them because of a few problems we are going to set up a development branch after releasing new version, so maybe you need to re base to latest stable master branch, you should be ok with already mined blocks. (you should also change src/P2p/P2pNetworks.h to random values other than ParsiCoin)

**Comment by yasaricli** [comment]
OK. compile the latest version again, thanks.

**Comment by ParsiCoin** [comment]
please also note that changing anything on src/P2p/P2pNetworks.h may cause problems with mined blocks so if you do this you should mine them again.

**Comment by yasaricli** [comment]
hmm, this **src/P2p/P2pNetworks.h** file was always the same.

**Comment by ParsiCoin** [comment]
it won't occur serious damages when your are using different parameters such as different ports, etc. but it's better if you change.

**Comment by yasaricli** [comment]
so we need to create a new "BYTECOIN_NETWORK" ?

**Comment by yasaricli** [comment]
ok, changed BYTECOIN_NETWORK. 

currently working fine. Thanks.
